[tool-black]
line-length = 200
include = ['*.py']

[tool.poetry]
name="code-snippet"
version="0.1.1"
description="Generate a code snippet from an input file"
authors=["Thomas Beer"]
readme="README.md"
